name: GitHub Pages CI

on:
  push:
    branches:
      - main  # Modify this branch name according to your repository's branch setup

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pkgdown
        run: Rscript -e "install.packages('pkgdown')"

      - name: Build site with pkgdown
        run: Rscript -e "pkgdown::build_site()"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # Modify this directory according to your pkgdown setup
