name: GitHub Pages CI

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Build site with pkgdown
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app rocker/r-ver:4.1.2 Rscript -e "install.packages('pkgdown', repos = 'https://cloud.r-project.org/')"
          docker run --rm -v ${{ github.workspace }}:/app -w /app rocker/r-ver:4.1.2 Rscript -e "pkgdown::build_site()"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
