name: GitHub Pages CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v1

      - name: Install pkgdown
        run: |
          sudo apt-get install -y pandoc
          Rscript -e "install.packages('pkgdown', repos = 'https://cloud.r-project.org/')"

      - name: Build site with pkgdown
        run: Rscript -e "pkgdown::build_site()"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
